# -*- coding: utf-8 -*-
"""task_4_datascience_the_spark_foundation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EsOrg-PZG-YN-9FNLUqQwc9K3WMDPYhq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

#loading dataset
df = pd.read_csv('/content/globalterrorismdb_0718dist.csv', low_memory=False, encoding='latin-1')

df.head()

df.shape

df.columns.values

df.describe()

df.info()

df.isnull().sum()

df.duplicated()

df.corr()

#checking for missing values
df.isnull().sum()

missing_values_percentage = df.isnull().sum()*100/len(df)
missing_values_percentage

#making a copy of original dataset
df2 = df.copy()

df2.head()

x = df2.dropna(axis =1, how = 'all')
x

data = df2.rename(columns={'eventid': 'Event_id','iyear':'Year','imonth':'Month','iday':"day",'gname':'Group','country_txt':'Country','region_txt':'Region','provstate':'State','city':'City','latitude':'latitude',
    'longitude':'longitude','summary':'summary','attacktype1_txt':'Attacktype','targtype1_txt':'Targettype','weaptype1_txt':'Weapon','nkill':'kill',
     'nwound':'Wound'},inplace=True)

data = df2[['Event_id','Year','Month','day','Country','State','Region','City','latitude','longitude',"Attacktype",'kill',
               'Wound','target1','summary','Group','Targettype','Weapon','motive']]

data.head()

data.shape

data.isnull().sum()

plt.subplots(figsize = (20,15))
sns.barplot(data['Country'].value_counts()[:10].index,data['Country'].value_counts()[:10].values,palette = 'plasma')
plt.title('Countries affected with maximum number of attacks',fontsize = 25)
plt.xlabel('Countries',fontsize=20)
plt.ylabel('Number of attacks', fontsize =15)
plt.xticks(rotation = 60)
plt.show()

year = data['Year'].unique()
years_count = data['Year'].value_counts(dropna = False)
plt.figure(figsize = (20,10))
sns.barplot(x = year,y = years_count,palette = "ocean")
plt.xlabel('Attacking Year',fontsize=20)
plt.ylabel('Number of Attacks',fontsize=20)
plt.title('Number of attacks in different years',fontsize =25)
plt.xticks(rotation = 50)
plt.show()

plt.subplots(figsize=(20,10))
sns.countplot(data["Attacktype"],order=data['Attacktype'].value_counts().index,palette="autumn")
plt.xticks(rotation=50,fontsize =10)
plt.xlabel("Attacktype",fontsize=20)
plt.ylabel("count",fontsize=20)
plt.title("Count of types of attack's",fontsize=25)
plt.show()

data[['Attacktype','kill']].groupby(["Attacktype"],axis=0).sum().plot(kind='bar',figsize=(18,10),color=['Green'])
plt.xticks(rotation=50)
plt.title("Number of people killed in different types of attack's",fontsize=20)
plt.ylabel('Number of people',fontsize=15)
plt.xlabel('Attack type',fontsize=15)
plt.show()

df2.plot(kind = 'scatter',x='Year', y='kill',color = 'black',figsize = (15,8))
plt.xlabel("year",fontsize=15)
plt.ylabel("Number of kills",fontsize =15) 
plt.title("Number of kills in years",fontsize = 20)
plt.show()

terror_region=pd.crosstab(df2.Year,df2.Region).plot(kind='area',stacked=False,figsize=(15,8))
terror_region.plot(color=sns.color_palette('brg',12))
plt.title('Terrorist Activities By Region',fontsize=25)
plt.ylabel('Number of Attacks',fontsize=20)
plt.xlabel("Year",fontsize=20)
plt.show()

Count_of_attacks = data['City'].value_counts().values[:10]
City = data['City'].value_counts().index[:10]

fig,ax = plt.subplots(figsize=(25, 10))
sns.barplot(x=City, y=Count_of_attacks, palette="rocket_r")
ax.set_ylabel(ylabel = 'Count of Attacks', fontsize = 15)
ax.set_xlabel(xlabel = 'Cities', fontsize = 15)
ax.set_title('Most Attacked Cities',fontsize=30)

data[['Group','kill']].groupby(['Group'],axis=0).sum().drop('Unknown').sort_values('kill',ascending=False).head(10).plot(kind='bar',color='skyblue',figsize=(18,10))
plt.title("Top 10 Terrorist group attack",fontsize=25)
plt.xlabel("Terrorist group name",fontsize=20)
plt.ylabel("No of people killed",fontsize=20)
plt.xticks(rotation = 90)
plt.show()

weapontypekill = data.pivot_table(columns='Weapon', values='kill', aggfunc='sum')
weapontypekill

labels = weapontypekill.columns.tolist() # convert line to list
transpoze = weapontypekill.T # transpoze
values = transpoze.values.tolist()
fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(aspect="equal"))
plt.pie(values, startangle=90, autopct='%.2f%%')
plt.title('Types of weapons used that caused deaths',fontsize = 25)
plt.legend(labels, loc='upper right', bbox_to_anchor = (2.2, 0.9), fontsize=15) # location legend
plt.show()

attack = data.Country.value_counts()[:10]
print("Top 10 Countries with maximum number of attacks done are : ")
attack

#value count of attacks carried out by the terrorist organisations
print("Terrorist group's with most attacks :")
df2.Group.value_counts()[1:15]

#@title Default title text
print("Most weapons used by terrorists to attack :")
df2.Weapon.value_counts()[0:15]