# -*- coding: utf-8 -*-
"""task3_datascience_the_spark_foundation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jIxqpbykDktX3mIbq4ZnQ_XlJ7LbYage
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')

df = pd.read_csv("/content/SampleSuperstore.csv")

df.head()

df.drop('Country', axis=1, inplace=True)
df.head()

df.shape

df.describe()

df['Quantity'].count()

num_bins = 8
plt.hist(df['Ship Mode'], num_bins, facecolor ='blue' , alpha = 0.8)
plt.show()

num_bins = 8
plt.hist(df['Segment'], num_bins, facecolor ='Red' , alpha = 0.9)
plt.show()

num_bins = 30
plt.hist(df['Postal Code'], num_bins, facecolor ='orange' , alpha = 0.8)
plt.show()

num_bins = 8
plt.hist(df['Category'], num_bins, facecolor ='purple' , alpha = 0.8)
plt.show()

num_bins = 15
plt.hist(df['Discount'], num_bins, facecolor ='green' , alpha = 0.8)
plt.show()

num_bins = 30
plt.hist(df['Postal Code'], num_bins, facecolor ='blue' , alpha = 0.8)
plt.show()

sales_by_region = df.groupby('Region').size()
print(sales_by_region)

plot_by_region = sales_by_region.plot(title='Sales by Region',xticks=(1,2,3,4))
plot_by_region.set_xlabel('Region')
plot_by_region.set_ylabel('Sales')

sales_by_profit = df.groupby('Profit').size()
print(sales_by_profit)

plot_by_profit = sales_by_profit.plot(title='Sales by Profit', xticks = range(0, 30))
plot_by_profit.set_xlabel('Profit')
plot_by_profit.set_ylabel('Sales')

sales_by_category = df.groupby('Category').size()
print(sales_by_category)

plot_by_category = sales_by_category.plot(title='Sales by Category')
plot_by_category.set_xlabel('Category')
plot_by_category.set_ylabel('Sales')

sales_by_shipmode = df.groupby('Ship Mode').size()
print(sales_by_shipmode)

sales_by_shipmode = sales_by_shipmode.plot(title='Sales by Ship Mode')
sales_by_shipmode.set_xlabel('Ship Mode')
sales_by_shipmode.set_ylabel('Sales')

sales_by_segment = df.groupby('Segment').size()
print(sales_by_segment)

sales_by_segment = sales_by_segment.plot(title='Sales by Segment')
sales_by_segment.set_xlabel('Segment')
sales_by_segment.set_ylabel('Sales')

# Plotting the distribution of Quantity v/s Sales
df.plot(x='Quantity', y='Sales', style='^')
plt.title('Quantity vs Sales')  
plt.xlabel('Quantity')  
plt.ylabel('Sales')  
plt.show()

# Plotting the distribution of Discount v/s Sales
df.plot(x='Discount', y='Sales', style='o')
plt.title('Discount vs Sales')  
plt.xlabel('Discount')  
plt.ylabel('Sales')  
plt.show()

# Plotting the distribution of Discount
df.plot(x='Profit', y='Sales', style='o')
plt.title('Discount vs Profit')  
plt.xlabel('Discount')  
plt.ylabel('Profit')  
plt.show()